Repository amperser/proselint, pull requests merged in 2021-07, with the labels that each got.

#1182 add exceptions for existence_check
  proselint/tools.py
  tests/test_existence_check.py
  tests/test_tools.py
Labels: cat: maintenance, priority: high, status: review-ready, type: feat, version: major

#1174 use regex for lexical illusions
  proselint/checks/lexical_illusions/misc.py
  tests/test_lexical_illusions.py
Labels: priority: null, status: review-ready, type: refactor, version: patch

#935 use click testing for cli unit tests
  tests/_test_version.py
  tests/test_demo.py
  tests/test_exit_codes.py
  tests/test_illegal_chars.py
Labels: cat: maintenance, priority: low, status: review-ready, type: test

#691 fix(checks): ignore case in misc.but for lowercase "but"
  proselint/checks/misc/but.py
  tests/test_misc_but.py
Labels: bug: confirmed, cat: false-positive, cat: maintenance, priority: high, status: review-ready, type: fix, version: patch

#1173 feat: implement project-wide proselintrc
  proselint/command_line.py
  proselint/tools.py
  tests/test_config_flag.py
Labels: cat: maintenance, priority: low, status: review-ready, type: feat, version: minor

#1176 test: bypass cache in pytest runs
  tests/check.py
Labels: cat: maintenance, status: review-ready, type: test

#1183 chore: fix package metadata
  .bumpversion.cfg
  .github/workflows/ci-lint-test.yml
  README.md
  poetry.lock
  proselint/version.py
  pyproject.toml
  setup.py
Labels: cat: maintenance, priority: urgent, status: review-ready, type: chore

#1184 ci: fix jekyll location for site building
  .github/workflows/cd-site.yml
Labels: priority: low, status: review-ready, type: ci

#1192 fix: correct false positives for lexical illusion regex
  proselint/checks/lexical_illusions/misc.py
  tests/test_lexical_illusions.py
Labels: bug: fixed-in-next, cat: false-positive, priority: urgent, status: merge-ready, type: fix, version: patch

#1195 build: fix package bundling to include proselintrc and tests
  pyproject.toml
Labels: cat: maintenance, priority: urgent, status: review-ready, type: build, version: patch

#1199 docs: update release instructions
  RELEASE.md
Labels: cat: maintenance, priority: null, status: review-ready

#620 fix(checks): make am_pm check case sensitive
  proselint/checks/dates_times/am_pm.py
  tests/test_dates_times_am_pm.py
  tests/test_existence_check.py
Labels: bug: confirmed, cat: false-positive, priority: low, status: wip, type: fix, version: patch
