Repository amperser/proselint, pull requests merged in 2021-05, with the labels that each got.

#1166 coveralls -> codecov
  .github/workflows/ci-lint-test.yml
  codecov.yml
  poetry.lock
  pyproject.toml
Labels: priority: high, status: review-ready, type: ci

#1081 feat: add --config cli argument
  .github/workflows/ci-danger.yml
  proselint/command_line.py
  proselint/tools.py
  tests/test_config_flag.py
  tests/test_config_flag_proselintrc
Labels: priority: medium, status: review-ready, type: feat, version: minor

#985 Fix incorrectly placed mondegreen
  proselint/checks/mondegreens/misc.py
Labels: bug: confirmed, cat: false-positive, priority: low, status: merge-ready, type: fix, version: patch

#1170 test: add curly quotes test for typography
  proselint/checks/typography/symbols.py
  tests/test_typography_symbols.py
Labels: cat: maintenance, priority: medium, status: merge-ready, type: test, version: patch
