Repository amperser/proselint, pull requests merged in 2021-11, with the labels that each got.

#1217 fix: make memoize safe for args/kwargs
  proselint/tools.py
Labels: bug: confirmed, type: fix, priority: high, version: patch, status: review-ready, cat: maintenance

#1218 refactor: convert max_errors to decorator
  proselint/checks/cliches/hell.py
  proselint/checks/misc/pretension.py
  proselint/checks/misc/suddenly.py
  proselint/checks/mixed_metaphors/misc.py
  proselint/checks/typography/exclamation.py
  proselint/checks/typography/symbols.py
  proselint/checks/weasel_words/very.py
  proselint/tools.py
Labels: type: refactor, priority: high, version: minor, status: review-ready, cat: maintenance

#1188 feat: convert meta-checks to decorators
  proselint/checks/typography/exclamation.py
  proselint/tools.py
Labels: type: feat, priority: high, version: minor, status: review-ready, cat: maintenance

#1246 fix: load default config if none specified
  proselint/tools.py
Labels: bug: confirmed, type: fix, priority: high, version: patch, status: wip
