Repository amperser/proselint, pull requests merged in 2022-01, with the labels that each got.

#1261 docs: add refererence to Flymake
  README.md
Labels: priority: null, status: merge-ready

#1266 added additional spelling checks (fixed issue #922)
  poetry.lock
  proselint/checks/spelling/ally_ly.py
  proselint/checks/spelling/ance_ence.py
  proselint/checks/spelling/ely_ly.py
  proselint/checks/spelling/misc.py
  proselint/checks/spelling/ve_of.py
  proselint/config.py
  tests/test_config_flag_proselintrc
  tests/test_spelling_ally_ly.py
  tests/test_spelling_ance_ence.py
  tests/test_spelling_ely_ly.py
  tests/test_spelling_ve_of.py
Labels: type: feat, priority: low, version: minor, status: review-ready, cat: maintenance

#1267 chore: remove unneeded six and future deps
  app.py
  poetry.lock
  proselint/checks/links/broken.py
  pyproject.toml
  scripts/insert_demo.py
  tests/test_existence_check.py
  tests/test_strunk_white_eos.py
Labels: type: chore, priority: low, version: patch, status: postponed, cat: maintenance, cat: deps
